default:
  image: python:3.10
  cache:
    paths:
      - .pip-cache/
  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install --upgrade setuptools[core]
    - pip install --upgrade build twine

stages:
  - build
  - test
  - publish

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

build:
  stage: build
  script:
    - python -m build --wheel
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script:
    - pip install --upgrade pytest
    - pip install --upgrade tree-sitter@git+https://github.com/tree-sitter/py-tree-sitter@v0.25.0
    - pip install dist/*.whl
    - pytest

publish:
  stage: publish
  script:
    - TWINE_PASSWORD=${PYPI_TOKEN} TWINE_USERNAME=__token__ python -m twine upload dist/*
  rules:
    - if: $CI_COMMIT_TAG
