# SPDX-FileCopyrightText: 2022 Christoph Sax <c_sax@mailbox.org>
#
# SPDX-License-Identifier: MIT

name: Create release

on:
  push:
    tags: ["v*"]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    uses: tree-sitter/workflows/.github/workflows/release.yml@main

  query:
    name: Validate queries
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v6

      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2

      - name: Build parser
        run: tree-sitter build

      - name: Set up ts_query_ls
        run: curl -fL https://github.com/ribru17/ts_query_ls/releases/latest/download/ts_query_ls-x86_64-unknown-linux-gnu.tar.gz | tar -xz

      - name: Check queries
        run: ./ts_query_ls check -f queries/
